### ISSUE TITLE
Installation on current yunohost version fails

### ISSUE THREAD

**Issue by Dorifer** [YunoHost-Apps/tandoor_ynh#11]
### Describe the bug

Unable to install tandoor app on current yunohost

### Context

- Hardware: *VPS
- YunoHost version: 11.0.9.13
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: current version

### Steps to reproduce

sudo yunohost app install tandoor

### Expected behavior

installation of the app

### Logs

Output of installation log see https://paste.yunohost.org/raw/eviwohevol

**Comment by nukeop** [comment]
Yep, I can't install it either

**Comment by nukeop** [comment]
No problem, take your time. This looks exactly like a program that I wanted to have and couldn't find for some time, so I'm really interested in it.

**Comment by navanchauhan** [comment]
Can you try the testing branch (I will push it to master soon)

**Comment by ericgaspar** [comment]
should be fixed
