### ISSUE TITLE
How to hide DJDT toolbar?

### ISSUE THREAD

**Issue by johndoe0815** [YunoHost-Apps/tandoor_ynh#21]
### Describe the bug

Whenever I open tandoor, even on the logon screen, the right side shows this DJDT toolbar with "debug" information. I can hide it, but it still floats with its icon on the right side. And when I open tandoor in a new broser, the toolbar is displayed again. How can this be hidden completely, it confuses other users?

### Context

Fresh tandoor install on yunohost

### Steps to reproduce

Install tandoor on yunohost and open it.

### Expected behavior

No default toolbar with debug information that is not relevant for a normal user.

**Comment by navanchauhan** [comment]
Whoops, I should have disabled the debug option. I will push an update tomorrow

**Comment by johndoe0815** [comment]
There seems to be still no update?!
