### ISSUE TITLE
Upgrade to 1.4.7

### ISSUE THREAD

**Issue by gihov** [YunoHost-Apps/tandoor_ynh#24]
Hi,

Would it be possible to upgrade to latest version available ? Since there is no major change only editing [conf/app.src](https://github.com/YunoHost-Apps/tandoor_ynh/blob/fbdbab37561b07e9b9f013256dcdf7d1ddfcb122/conf/app.src) seems to be fine.

Thanks

**Comment by navanchauhan** [comment]
The auto-updater should’ve kicked in. I will look into it tomorrow.

**Comment by gihov** [comment]
From what I see quickly at least the "exit" should be removed : https://github.com/YunoHost-Apps/tandoor_ynh/blob/master/.github/workflows/updater.sh#L13

**Comment by navanchauhan** [comment]
oh my lord, that was such a basic oversight haha

**Comment by navanchauhan** [comment]
closing this as I have just enabled the auto-updater

**Comment by gihov** [comment]
Even if the app is marked as 1.4.8 in yunohost the package installed is still 1.4.5. The file conf/app.src has not been updated by the CI-CD.

**Comment by gihov** [comment]
Could you reopen the issue @navanchauhan ?
