### ISSUE TITLE
Service missing permission to start

### ISSUE THREAD

**Issue by jaireimy** [YunoHost-Apps/tandoor_ynh#31]
Hi,

I installed you app on my YNH instance (11.1.16). 

I had an 'internal server error' message when I tried to access it the first time. So I tried to restart the tandoor service, but its unable to do so because of missing permissions.

Also you mentioned additional setup for the "superuser" is needed, but I have no clue. That would be nice to have some detailed instructions for this part.

Install logs: https://paste.yunohost.org/raw/epuzofekuh
Service logs: https://paste.yunohost.org/fozogamuba

**Comment by jaireimy** [comment]
Everything is working fine after the upgrade:

sudo yunohost app upgrade tandoor -u https://github.com/YunoHost-Apps/tandoor_ynh/tree/testing --debug

Thanks !

**Comment by navanchauhan** [comment]
I will look into creating more documentation for the superuser
