### ISSUE TITLE
Update from 1.4.8 breaks the installation

### ISSUE THREAD

**Issue by johndoe0815** [YunoHost-Apps/tandoor_ynh#35]
### Describe the bug

I have updated tandoor from 1.4.8 to 1.4.9 in yunohost.
During installation, the following was shown:

```
Updating a configuration file...
File /var/www/tandoor/recipes/version.py has been manually modified since the installation or last upgrade. So it has been duplicated in /var/cache/yunohost/appconfbackup//var/www/tandoor/recipes/version.py.backup.20230508.102241
[1m--- /var/cache/yunohost/appconfbackup//var/www/tandoor/recipes/version.py.backup.20230508.102241 2023-03-14 22:10:37.000000000 +0000[0m
[1m+++ /var/www/tandoor/recipes/version.py 2023-05-08 10:22:43.169996398 +0000[0m
[36m@@ -1,2 +1,2 @@[0m
[31m-VERSION_NUMBER = "0.0.0"[0m
[31m-BUILD_REF = ""[0m
[32m+VERSION_NUMBER = "1.4.9"[0m
[32m+BUILD_REF = ""[0m
\ No newline at end of file
Upgrading dependencies via pip...
Running migrations and generatic static files...
```

I have never modivied the version.py.

In the end the update was reported as a success. However now when opening tandoor, I only get a Server Error (500) displayed.

### Steps to reproduce

Update tandoor in yunohost.

**Comment by navanchauhan** [comment]
the error seems to suggest a checksum mismatch, but it should not affect the app itself

**Comment by navanchauhan** [comment]
In the meanwhile, you should be able to restore to the pre-upgrade version

**Comment by johndoe0815** [comment]
Thanks. I uninstalled and recovered the backup from 1.4.8., works again. So the update broke it indeed.

**Comment by johndoe0815** [comment]
Tried another update to the new version 1.4.11 from my current 1.4.8.
Same issue, Server Error 500 after the update.
This is the log from the update:
`tandoor wird jetzt aktualisiert...
Loading installation settings...
Backing up the app before upgrading (may take a while)...
Stopping a systemd service...
Making sure dedicated system user exists...
Upgrading source files...
Upgrading dependencies...
Upgrading NGINX web server configuration...
Updating a configuration file...
File /var/www/tandoor/recipes/version.py has been manually modified since the installation or last upgrade. So it has been duplicated in /var/cache/yunohost/appconfbackup//var/www/tandoor/recipes/version.py.backup.20230612.082517
[1m--- /var/cache/yunohost/appconfbackup//var/www/tandoor/recipes/version.py.backup.20230612.082517 2023-03-14 22:10:37.000000000 +0000[0m
[1m+++ /var/www/tandoor/recipes/version.py 2023-06-12 08:25:18.820622818 +0000[0m
[36m@@ -1,2 +1,2 @@[0m
[31m-VERSION_NUMBER = "0.0.0"[0m
[31m-BUILD_REF = ""[0m
[32m+VERSION_NUMBER = "1.4.11"[0m
[32m+BUILD_REF = ""[0m
\ No newline at end of file
Upgrading dependencies via pip...
Running migrations and generatic static files...
Building frontend...
warning " > workbox-webpack-plugin@5.1.4" has unmet peer dependency "webpack@^4.0.0".
warning "@vue/cli-service > @babel/helper-compilation-targets@7.20.7" has unmet peer dependency "@babel/core@^7.0.0".
warning " > @babel/eslint-parser@7.19.1" has unmet peer dependency "@babel/core@>=7.11.0".
warning " > @vue/composition-api@1.7.1" has incorrect peer dependency "vue@>= 2.5 < 2.7".
warning " > babel-loader@9.1.2" has unmet peer dependency "@babel/core@^7.12.0".
warning " > babel-loader@9.1.2" has unmet peer dependency "webpack@>=5".
warning "bootstrap-vue > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > workbox-webpack-plugin@6.5.4" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
warning " > @typescript-eslint/eslint-plugin@4.33.0" has incorrect peer dependency "@typescript-eslint/parser@^4.0.0".
- Building for production...
(node:738171) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)
[BABEL] Note: The code generator has deoptimised the styling of /var/www/tandoor/vue/src/utils/openapi/api.ts as it exceeds the max of 500KB.
(node:738171) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Upgrading systemd configuration...
Upgrading logrotate configuration...
Integrating service in YunoHost...
Starting a systemd service...
Reloading NGINX web server...
Upgrade of tandoor completed
tandoor aktualisiert
Upgrade vollständig`

I do not see any release notes and there is no more comments on this issue. What is the status on this?

**Comment by navanchauhan** [comment]
was busy with my classes, let me look into this now

**Comment by navanchauhan** [comment]
<img width="762" alt="image" src="https://github.com/YunoHost-Apps/tandoor_ynh/assets/29234112/cfb949ed-afbc-45ee-ae85-2834be2a2588">

It looks like the upgrade gets stuck on this step, and then eventually times out (but is returned as a success?) -> thus the server error

**Comment by navanchauhan** [comment]
@johndoe0815 what device are you running this on?

**Comment by johndoe0815** [comment]
> @johndoe0815 what device are you running this on?

I run YunoHost on Proxmox on a Fujitsu Futro S740.

**Comment by johndoe0815** [comment]
As I started to use tandoor outside of Yunohost in a separate docker container, I tried to uninstall and then freshly reinstall in Yunohost. Even that fresh install fails with invalid or unexpected token:
https://paste.yunohost.org/raw/rojibebiwo

This is too unreliable to use "productively" :-(

**Comment by aurore-finco** [comment]
Hi!
I have exactly the same problem, upgrading from 1.4.5 to current version (1.5.5). I restored 1.4.5 and it works.
Here is the log from the upgrade: https://paste.yunohost.org/raw/alixoyozuv
I run yunohost 11.2.4 on a Raspberry Pi 4B.

**Comment by ericgaspar** [comment]
should be fixed
