### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Pentaonia** [YunoHost-Apps/tandoor_ynh#53]
### Describe the bug

I am not able to install tandoor via the web ui from yunohost.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.5.5~ynh1

### Steps to reproduce
- Installation via web UI

### Expected behavior

- Working application at the end.

### Logs
https://paste.yunohost.org/raw/oqisezoyeb

**Comment by ericgaspar** [comment]
should be fixed
