### ISSUE TITLE
Can't edit recipes any more

### ISSUE THREAD

**Issue by der-bender** [YunoHost-Apps/tandoor_ynh#67]
### Describe the bug

I can't edit existing recipes any more. The tree dots for accessing the menu on the right side are simply missing. I'm logged in a superuser. Adding recipes works without problems. Unfortunately I can't tell since when I can't edit any more, just noticed it recently.

### Context

- Hardware: *VPS bought online (Contabo)*
- YunoHost version: 11.2.10
- I have access to my server: *Through SSH, through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using package version/branch: 1.5.13~ynh1/stable

### Steps to reproduce

I log in to Tandoor, open a recipe and want to edit.

### Expected behavior

Well, there should be three dots which could be clicked to open a menu.

### Logs

I'm not sure which logs to post here, sorry.

I did some research and found a report where someone else exactly describes my problem. His problem seems to be triggered by some user permission/container problem. Unfortunately I don't know how to apply this solution to my installation or even if it would help. Link to the report: https://github.com/TandoorRecipes/recipes/discussions/2912

**Comment by Mixata458** [comment]
@der-bender @Malbak Hello, did you manage to resolve your problem? I have the exact same problem, I've been searching for days without finding a solution.
THANKS

**Comment by der-bender** [comment]
Well, not really. But there's a workaround that enables you to edit a recipe: when viewing a recipe just replace "view" in the URL by "edit". 

Am 28. März 2024 16:16:51 MEZ schrieb Mixata458 ***@***.***>:

**Comment by Mixata458** [comment]
@der-bender yes I had seen this possibility, but I would still like to solve the problem.

**Comment by ballinger** [comment]
Same here.. any progress?

**Comment by Mixata458** [comment]
Hi, I didn't find a solution to the problem, so I installed TANDOOR on a Runtipi instance.
https://runtipi.io/

**Comment by mc-knife** [comment]
july 9th 2024: todays yunohost-tandoor-update (to  1.5.18~ynh1) fixed this for me.

**Comment by ballinger** [comment]
> july 9th 2024: todays yunohost-tandoor-update (to 1.5.18~ynh1) fixed this for me.

same here, resolved!
