### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Bcarr91** [YunoHost-Apps/tandoor_ynh#70]
### Describe the bug

**Install attempts causes VPS freeze; no other apps in Yunohost will work during the freeze, and the install will not complete. Attempted several times to install with failures.**

### Context

- Hardware: **VPS bought online**
- YunoHost version: **11.2.10.3 (stable)**
- I have access to my server: **Through SSH | through the webadmin**
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: **Yes**
  - If yes, please explain: **Application Installation**
- Using, or trying to install package version/branch: **1.5.13~ynh1**
- If upgrading, current package version: **N/A**

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. **N/A**
- If you used the webadmin, please perform the equivalent command from the CLI first.
- *If the error occurs in your browser, explain what you did:*
   **1. Go to Applications > Install
   2. Search for Tandoor
   3. Update Label from 'Tandoor' to 'Tandoor Recipes'
   4. Designate subdomain
   5. Allow Visitor Access
   6. Click 'Install'**

### Expected behavior

**Installation progress bar, with successful install.**

### Logs

**- Install attempt two days ago: https://paste.yunohost.org/raw/redalexibe
- Install attempt this morning: https://paste.yunohost.org/raw/venuliqupu

To note: I had to manually restart my VPS through their control panel during this morning's install as my whole VPS was frozen from the install; SSH access was unable to load.**

**Comment by Bcarr91** [comment]
There seems to possibly be a RAM issue to start; I increased my available RAM from 1 GB to 2 GB, and now the installer completes (but still fails). Some apps do have a "you should have more RAM" notice, but even these apps installed with little issue with 1 GB of RAM.

[Updated Error Log](https://paste.yunohost.org/raw/uqivefacak)

**Comment by ericgaspar** [comment]
ram requirements updated in manifest.toml
