### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by oleole39** [YunoHost-Apps/tandoor_ynh#75]
### Describe the bug

Installation failed in the process.
Note that he VPS used has not much RAM and I suspect the 50M RAM usage mentioned in the catalog to be actually higher. 

Not sure that this is relevant, but after the install attempt I was logged off (maybe because I left the Webadmin unattended too long).
Tandoor appeared in the application list as if it was installed (and I was later able to uninstall it).
Visiting the installed URL was leading to a page mentioning a HTTPS certificate error (I doubt this relates to an issue with the domain).

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.14.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.5.17~ynh1

### Steps to reproduce

Launched install on a dedicated subdomain via the webadmin.

### Logs

https://paste.yunohost.org/tigiyuseta.apache

**Comment by ericgaspar** [comment]
Tandoor needs 2.5G RAM to build... I updated manifest.toml accordingly
