### ISSUE TITLE
media files not accessible

### ISSUE THREAD

**Issue by ballinger** [YunoHost-Apps/tandoor_ynh#79]
### Describe the bug

media files probably have the wrong user credentials / pictures and media are not displayed
![Screenshot_20240711_082424](https://github.com/YunoHost-Apps/tandoor_ynh/assets/1741638/a24ad99f-b177-4b7a-9f57-1ff4e459c971)

### Context

- Hardware: computer
- YunoHost version: latest
- all standard
- tandoor 1.5.18~ynh1

```
/var/www/tandoor/source# ls -l
total 128
-rw-rw----  1 tandoor www-data  2929 Jul  8 18:13 boot.sh
-rw-rw----  1 tandoor www-data  2669 Jul  8 18:13 CONTRIBUTERS.md
drwxrwx--- 16 tandoor www-data  4096 Jul 10 06:44 cookbook
-rw-rw----  1 tandoor www-data  1478 Jul  8 18:13 Dockerfile
drwxrwx---  8 tandoor www-data  4096 Jul  8 18:13 docs
-rw-rw----  1 tandoor www-data 36742 Jul  8 18:13 LICENSE.md
-rw-rw----  1 tandoor www-data   860 Jul  8 18:13 make_compile_messages.py
-rwxrwx---  1 tandoor www-data   539 Jul  8 18:13 manage.py
drwxr-xr-x  3 tandoor tandoor   4096 Jul 10 10:21 mediafiles
```
```
ls -l staticfiles/
total 108
drwxr-xr-x 5 tandoor tandoor  4096 Jul 10 06:45 admin
drwxr-xr-x 2 tandoor tandoor  4096 Jul 10 06:45 assets
drwxr-xr-x 2 tandoor tandoor  4096 Jul 10 06:45 css
```
`chown tandoor:www-data mediafiles/ -R` does not work
all new files, inside mediafiles/ - created from the web interface sets the user to tandoor:tandoor 

### Steps to reproduce
   1. create new recipie
   2. drag image into pic placeholder and save
   3. image will be broken not accessible

### Expected behavior

show pictures

### Logs

no logs under /var/log/tandoor

**Comment by ballinger** [comment]
# media issues
* nginx is set to wrong media dir?
```
/etc/nginx/conf.d/domain.org.d/tandoor.conf
location /media/ {
  alias /var/www/tandoor/mediafiles;

```
my default install has this dir in `/var/www/tandoor/source/mediafiles`

# user rights
changing the media dir + content to tandoor:www-data doesnt help
changing the systemctl usergroup to www-data doesnt help

**Comment by ballinger** [comment]
nano /var/www/tandoor/.env
```
# If mediafiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# MEDIA_URL=/media/
MEDIA_URL=https://domain.org:8097/source/media/
```
* this removes the http 404 error, but the img is still not showing up - firefox does not report any errors anymore...

**Comment by mubbelsberger** [comment]
I've got the same problem and tried messing with the Recipes.conf. 

But no success.

[See my thread in the yunohost forum](https://forum.yunohost.org/t/tandoor-recipes-images-not-showing-up/30476).

**Comment by ericgaspar** [comment]
closing with #80
