### ISSUE TITLE
404 error when loading images

### ISSUE THREAD

**Issue by DetectiveBrie** [YunoHost-Apps/tandoor_ynh#8]
### Describe the bug

When uploading an image for a recipe, it is successfully present in the /var/www/tandoor/mediafiles folder, but trying to access it as a static file leads to a 404.

### Context

- Hardware: Online VPS OVH
- YunoHost version: 11.0.9.7
- I have access to my server: SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Create a recipe, upload an attached picture in the editor. It will not show as it leads to a 404 once uploaded.

**Comment by navanchauhan** [comment]
Thank you for filing this issue, looks like I might have not pushed the correct Nginx configuration. 

I recall having that issue and I thought I had fixed it. 


I'm travelling right now, but as soon as I have some bandwidth, I'll test it out again and push an update

**Comment by navanchauhan** [comment]
Please reopen if the issue still persists. Fixed with #9 and #10
